### ISSUE TITLE
关于登陆的一些问题

### ISSUE THREAD

**Issue by doublezhuang101** [chenyongzhe/Qt-studentmanager#2]
我现在也在用VS+QT+MySQL写一个类似的课设，但是关于QT链接MySQL操作不是很明白，想看看你的工程学习，但clone了你的工程之后因为卡在登陆界面导致不能再进一步看，所以想知道怎么删除这个登陆的部分，或是不使用账号登陆。文档中对登陆方面说的不是很清楚

**Comment by chenyongzhe** [comment]
https://blog.csdn.net/qq_35158695/article/details/53022565

**Comment by chenyongzhe** [comment]
登录在mainwindow.cpp文件里
